fix eager creation for associations by adding where clause
gobuffalo/pop pull request #607
Opened 2020-12-04 20:41 UTC by xixinjie

# Problem
When try to use `db.Eager().ValidateAndCreate(user)` to create a user and underlying `has_many` books, it succeeded for the first time when books table is empty, but failed to save the books in following creations.

# How to fix
Add where clause when check if the books exist as shown in the PR.
```go
whereCondition, args := after[index].Constraint()
exists, errE := Q(c).Where(whereCondition, args...).Exists(i)
```

# Samples
```go
type User struct {
	ID string `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
	Books []Book `json:"books" has_many:"books" fk_id:"user_id"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

type Book struct {
	ID string `json:"id" db:"id"`
	Name string `json:"name" db:"name"`

	UserID string `json:"user_id" db:"user_id"`
	User *User `json:"user" belongs_to:"users"`

	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}
```

```go
	u := &User{
		ID:        "1",
		Name:      "Foo",
		Books:     []Book{{
			ID:        "1",
			Name:      "Hello World!",
		}},
	}

	vErrs, err := db.Eager().ValidateAndCreate(u)
	if err != nil {
		panic(fmt.Sprintf("failed to create user: %s", err))
	}

	if vErrs.HasAny() {
		panic(fmt.Sprintf("failed to match validation: %s", vErrs))
	}

	log.Printf("created a new user: %s", u.ID)
```

SQL logs:
```
sql - INSERT INTO `users` (`created_at`, `id`, `name`, `updated_at`) VALUES (:created_at, :id, :name, :updated_at)
sql - SELECT EXISTS (SELECT books.created_at, books.id, books.name, books.user_id, books.updated_at FROM books AS books WHERE user_id = ?) | ["1"]
INSERT INTO `books` (`created_at`, `id`, `name`, `user_id`, `updated_at`) VALUES (:created_at, :id, :name, :user_id, :updated_at)
```

2021-01-04 13:41 UTC, xixinjie commented
@stanislas-m @markbates any chance to review or any suggestion?

2021-01-04 14:15 UTC, aeneasr requested changes
Thank you, could you please add a failing test case first which shows the behaviour you describe - first to verify your findings and second to verify your fix!

2021-01-04 14:15 UTC, aeneasr commented on executors.go
> +							exists, errE := Q(c).Where("id = ?", id).Exists(i)
The ID column is variable depending on the struct and should therefore not be hardcoded. `sm` has a function `whereID` which should be used instead.

2022-09-18 14:36 UTC, sio4 commented
Hello @xixinjie,

Thank you for reporting this issue and contribution. I took a look at the issue and definitely the original usage was problematic. Please resolve the review comment, then I will take care of the next steps along with test cases.

I am not sure if you still have an interest in this issue. If you do not respond, I will take over this issue.

2022-09-24 05:04 UTC, merged

2022-09-24 05:13 UTC, sio4 reviewed
LGTM

minor fix will be on another PR.